travis:
  secure:
    BINSTAR_TOKEN: eG3GDDaNmtZybzHSHOMoFcd6P8n+M90VnwlHsAW6nookkAxqvq/OeJJEFSUTcrPXEPZFDi3q9RVMwBRB4Qg+gxisElDgpGJrwRtNKS37/ysdIvBodzSK/xi4zXapYe9yZGAvK9rz/iblKapquMcNhh6mQOviGATfa/4sclUBiuTgTFsHaNdyl0ZsTgJ+kjsJDt9v8sFHsg2U2q/+o3N/HI7aU87FJZF0b1KMdJlq0Ch2Rf+Ps0aW/UVA2PrKsFfOlj54JGywWHtmJyjsQ8B734JvegRZBh2icwvbRxyT9lEoOc/D4einRW0zvSAPOY5f85wKNUmfV4LX2dgvf/7cBlUHqmsTE/v2mH/ftkCWDaM4mRLHp0lvuiw4xfbetj1veFuHTqYNWlUcRluc8qYtBKYntE05JpSiCH4kcL425jQNohFGetvz0KxJumPKgma4rljb0m/cTTc1tqseP95sdkKHKSOJnYAXBXEee4Udmu9n7hvYbxUUCLrnJLusaMQkTN4ltBtBoqHKi4SmHBjUrtLvLsgSiN2KjU4PMUfsALhzCqCqOBxBa4youIqzTGCkwOoFsem0NRVB27eLNsPCSGUd24Tg5vZTMsrIXhSZ1Nq/DiW9aZfIpsQ9TDHMTb79FWPrD/F2BplbYLOJmJvk+jkF1uQK1HCzD/784qiTFkc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
